#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
touch hull.foam

mkdir -p constant/triSurface

cp -f hull.stl constant/triSurface/

runApplication blockMesh

runApplication surfaceFeatureExtract

runApplication decomposePar

runParallel snappyHexMesh -overwrite

runParallel redistributePar -reconstruct -constant -overwrite

runApplication renumberMesh -constant -overwrite

#------------------------------------------------------------------------------